### ISSUE TITLE
`sourcePullRequest.title` contains escaped characters

### ISSUE THREAD

**Issue by azatoth** [sorenlouv/backport#490]
I have following setting in my `.backportrc.json`:

```json
{
  "prTitle": "{{sourcePullRequest.title}} | backport for {{targetBranch}}"
}
```

If the original pull request had a title like `Don't do X and Y`, the backport's title now becomes `Don&#x27;t do X and Y |backport for myBranch`.

**Comment by azatoth** [comment]
So this isn't actually a issue as I didn't realize first it's Handlebars, and I should just have used triple brackets instead

**Comment by sorenlouv** [comment]
Sorry for the slow reply. Glad you got it solved!

**Comment by azatoth** [comment]
> Sorry for the slow reply. Glad you got it solved!

No problem; I realized I could fix my problem by using  `{{{sourcePullRequest.title}}}` instead. Though I assume the more permanent and proper solution is to add  `{noEscape: true}` option to `Handlebars.compile()`

**Comment by sorenlouv** [comment]
Fixed in https://github.com/sorenlouv/backport/pull/495
