### ISSUE TITLE
providing terminal editor during conflicts hangs the process

### ISSUE THREAD

**Issue by kapral18** [sorenlouv/backport#499]
when providing editor like nano or (n)vim
during a cherry pick conflict resolution I never get to the listing of files
to resolve

it hangs one step before.

![image](https://github.com/sorenlouv/backport/assets/1625373/4ab7c667-60ab-4027-8980-2c5034385220)

And waits for a stdin input, which is understandable because nvim as any terminal editor is operating in interactive mode
and expecting stdin to be continuously fed.

Since `child_process.spawn`s default `stdio` option is `pipe` it creates an indirection layer between parent and child pipes, making nvim or any other editor hang disconnected while waiting for any input.

One way of fixing this would be to add `stdio: inherit` to `spawn`, to remove the unnecessary pipe layer and connect child process to parent io pipes.

I already tested it and it indeed works. Let me know wdyt.

Thanks

**Comment by sorenlouv** [comment]
Hi @kapral18 

> I already tested it and it indeed works. Let me know wdyt.

Can you open a PR? Don't worry about failing test, I'll gladly help out with that.
