### ISSUE TITLE
"sourceBranch" not working in local config?

### ISSUE THREAD

**Issue by rasky** [sorenlouv/backport#516]
I've created a local config file as follows:

```json
{
    "repoOwner": "DragonMinded",
    "repoName": "libdragon",
    "targetBranchChoices": [{ "name": "trunk", "checked": true }],
    "sourceBranch": "preview",
    "multipleCommits": true
}
```

My global config only contains the access token. When I run `backport` with no arguments, the tool fetches the remote commits from the default branch (`trunk`) and shows me the list of trunk commits to select for backport. If I instead run the tool with `backport --sourceBranch=preview`, everything works as expected. 

I'm running backport 9.6.1.

**Comment by sorenlouv** [comment]
Thanks for raising this. I'll take a look. Until then can you try with `backport --skipRemoteConfig` and see if that makes a difference?
